import { Account, Client, Databases } from 'appwrite';

// Environment variables
const {
  VITE_APPWRITE_ENDPOINT,
  VITE_APPWRITE_PROJECT_ID,
  VITE_APPWRITE_DATABASE_ID,
  VITE_APPWRITE_ADMIN_USER_ID,
  VITE_APPWRITE_COMPANY_SETTINGS_COLLECTION_ID,
  VITE_APPWRITE_SERVICES_COLLECTION_ID,
  VITE_APPWRITE_TEAM_COLLECTION_ID,
  VITE_APPWRITE_CONTACTS_COLLECTION_ID,
  VITE_APPWRITE_FAQS_COLLECTION_ID,
  VITE_APPWRITE_SUBSCRIPTIONS_COLLECTION_ID,
  VITE_APPWRITE_PARTNERS_COLLECTION_ID,
  VITE_APPWRITE_REGIONS_COLLECTION_ID,
  VITE_APPWRITE_USPS_COLLECTION_ID,
  VITE_APPWRITE_PROJECTS_COLLECTION_ID,
  VITE_APPWRITE_SEND_EMAIL_FUNCTION_ID,
} = import.meta.env;

// Initialize the Appwrite client
const client = new Client();
client.setEndpoint(VITE_APPWRITE_ENDPOINT).setProject(VITE_APPWRITE_PROJECT_ID);

// Initialize Appwrite services
const databases = new Databases(client);
const account = new Account(client);

// Export database ID
export const DATABASES = {
  MAIN: VITE_APPWRITE_DATABASE_ID,
};

// Project
export const PROJECT_ID = VITE_APPWRITE_PROJECT_ID;

export const EMAIL_FUNCTION_ID = VITE_APPWRITE_SEND_EMAIL_FUNCTION_ID;

// Export collection IDs
export const COLLECTIONS = {
  COMPANY_SETTINGS: VITE_APPWRITE_COMPANY_SETTINGS_COLLECTION_ID,
  SERVICES: VITE_APPWRITE_SERVICES_COLLECTION_ID,
  TEAM: VITE_APPWRITE_TEAM_COLLECTION_ID,
  CONTACTS: VITE_APPWRITE_CONTACTS_COLLECTION_ID,
  FAQS: VITE_APPWRITE_FAQS_COLLECTION_ID,
  SUBSCRIPTIONS: VITE_APPWRITE_SUBSCRIPTIONS_COLLECTION_ID,
  PARTNERS: VITE_APPWRITE_PARTNERS_COLLECTION_ID,
  REGIONS: VITE_APPWRITE_REGIONS_COLLECTION_ID,
  USPS: VITE_APPWRITE_USPS_COLLECTION_ID,
  PROJECTS: VITE_APPWRITE_PROJECTS_COLLECTION_ID,
};

// Export other constants (like Admin user ID)
export const ADMIN = {
  USER_ID: VITE_APPWRITE_ADMIN_USER_ID,
};

// Export Appwrite services
export { client, databases, account };
