// appwrite.ts

import { Account, Client, Databases } from 'appwrite';

// Environment variables
const {
  VITE_APPWRITE_ENDPOINT,
  VITE_APPWRITE_PROJECT_ID,
  VITE_APPWRITE_DATABASE_ID,
  VITE_APPWRITE_ADMIN_USER_ID,
  VITE_APPWRITE_ORGANIZATION_SETTINGS_COLLECTION_ID,
  VITE_APPWRITE_SERVICES_COLLECTION_ID,
  VITE_APPWRITE_TEAM_COLLECTION_ID,
  VITE_APPWRITE_CONTACTS_COLLECTION_ID,
  VITE_APPWRITE_FAQS_COLLECTION_ID,
  VITE_APPWRITE_INQUIRIES_COLLECTION_ID,
  VITE_APPWRITE_NEWS_COLLECTION_ID,
  VITE_APPWRITE_CORE_VALUES_COLLECTION_ID,
  VITE_APPWRITE_SEND_EMAIL_FUNCTION_ID,
} = import.meta.env;

// Initialize the Appwrite client
const client = new Client();
client.setEndpoint(VITE_APPWRITE_ENDPOINT).setProject(VITE_APPWRITE_PROJECT_ID);

// Initialize Appwrite services
const databases = new Databases(client);
const account = new Account(client);

// Export database ID
export const DATABASES = {
  MAIN: VITE_APPWRITE_DATABASE_ID,
};

// Project
export const PROJECT_ID = VITE_APPWRITE_PROJECT_ID;

export const EMAIL_FUNCTION_ID = VITE_APPWRITE_SEND_EMAIL_FUNCTION_ID;

// Export collection IDs
export const COLLECTIONS = {
  ORGANIZATION_SETTINGS: VITE_APPWRITE_ORGANIZATION_SETTINGS_COLLECTION_ID,
  SERVICES: VITE_APPWRITE_SERVICES_COLLECTION_ID,
  TEAM: VITE_APPWRITE_TEAM_COLLECTION_ID,
  CONTACTS: VITE_APPWRITE_CONTACTS_COLLECTION_ID,
  FAQS: VITE_APPWRITE_FAQS_COLLECTION_ID,
  INQUIRIES: VITE_APPWRITE_INQUIRIES_COLLECTION_ID,
  NEWS: VITE_APPWRITE_NEWS_COLLECTION_ID,
  CORE_VALUES: VITE_APPWRITE_CORE_VALUES_COLLECTION_ID,
};

// Optional: Export other constants (like Admin user ID)
export const ADMIN = {
  USER_ID: VITE_APPWRITE_ADMIN_USER_ID,
};

// Export Appwrite services
export { client, databases, account };
